global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'monitor-sintesis'

scrape_configs:
  - job_name: 'monitor-sintesis'
    scrape_interval: 5s
    metrics_path: /management/prometheus
    static_configs:
      - targets:
          - monitor:8080
        labels:
          application: 'Monitor Sintesis'
